import 'package:flutter/material.dart';
List<Map<String,Object>> list=[
  {
    'itemColor': Colors.white,
    'isFav':false,
    "albumId": 1,
    "id": 1,
    "title": "accusamus beatae ad facilis cum similique qui sunt",
    "url": "https://via.placeholder.com/600/92c952",
    "thumbnailUrl": "https://via.placeholder.com/150/92c952"
  },
  {
    'isFav':false,
    'itemColor': Colors.white,
    "albumId": 1,
    "id": 2,
    "title": "reprehenderit est deserunt velit ipsam",
    "url": "https://via.placeholder.com/600/771796",
    "thumbnailUrl": "https://via.placeholder.com/150/771796"
  },
  
  {
    'isFav':false,
    "albumId": 1,
    'itemColor': Colors.white,
    "id": 3,
    "title": "officia porro iure quia iusto qui ipsa ut modi",
    "url": "https://via.placeholder.com/600/24f355",
    "thumbnailUrl": "https://via.placeholder.com/150/24f355"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 4,
    'itemColor': Colors.white,
    "title": "culpa odio esse rerum omnis laboriosam voluptate repudiandae",
    "url": "https://via.placeholder.com/600/d32776",
    "thumbnailUrl": "https://via.placeholder.com/150/d32776"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 5,
    'itemColor': Colors.white,
    "title": "natus nisi omnis corporis facere molestiae rerum in",
    "url": "https://via.placeholder.com/600/f66b97",
    "thumbnailUrl": "https://via.placeholder.com/150/f66b97"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 6,
    'itemColor': Colors.white,
    "title": "accusamus ea aliquid et amet sequi nemo",
    "url": "https://via.placeholder.com/600/56a8c2",
    "thumbnailUrl": "https://via.placeholder.com/150/56a8c2"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 7,
    'itemColor': Colors.white,
    "title": "officia delectus consequatur vero aut veniam explicabo molestias",
    "url": "https://via.placeholder.com/600/b0f7cc",
    "thumbnailUrl": "https://via.placeholder.com/150/b0f7cc"
  },
  {
    'isFav':false,
    "albumId": 1,
    'itemColor': Colors.white,
    "id": 8,
    "title": "aut porro officiis laborum odit ea laudantium corporis",
    "url": "https://via.placeholder.com/600/54176f",
    "thumbnailUrl": "https://via.placeholder.com/150/54176f"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 9,
    'itemColor': Colors.white,
    "title": "qui eius qui autem sed",
    "url": "https://via.placeholder.com/600/51aa97",
    "thumbnailUrl": "https://via.placeholder.com/150/51aa97"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 10,
    'itemColor': Colors.white,
    "title": "beatae et provident et ut vel",
    "url": "https://via.placeholder.com/600/810b14",
    "thumbnailUrl": "https://via.placeholder.com/150/810b14"
  },
  {
    'isFav':false,
    "albumId": 1,
    'itemColor': Colors.white,
    "id": 11,
    "title": "nihil at amet non hic quia qui",
    "url": "https://via.placeholder.com/600/1ee8a4",
    "thumbnailUrl": "https://via.placeholder.com/150/1ee8a4"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 12,
    'itemColor': Colors.white,
    "title": "mollitia soluta ut rerum eos aliquam consequatur perspiciatis maiores",
    "url": "https://via.placeholder.com/600/66b7d2",
    "thumbnailUrl": "https://via.placeholder.com/150/66b7d2"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 13,
    'itemColor': Colors.white,
    "title": "repudiandae iusto deleniti rerum",
    "url": "https://via.placeholder.com/600/197d29",
    "thumbnailUrl": "https://via.placeholder.com/150/197d29"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 14,
    'itemColor': Colors.white,
    "title": "est necessitatibus architecto ut laborum",
    "url": "https://via.placeholder.com/600/61a65",
    "thumbnailUrl": "https://via.placeholder.com/150/61a65"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 15,
    'itemColor': Colors.white,
    "title": "harum dicta similique quis dolore earum ex qui",
    "url": "https://via.placeholder.com/600/f9cee5",
    "thumbnailUrl": "https://via.placeholder.com/150/f9cee5"
  },
  {
    'isFav':false,
    "albumId": 1,
    'itemColor': Colors.white,
    "id": 16,
    "title": "iusto sunt nobis quasi veritatis quas expedita voluptatum deserunt",
    "url": "https://via.placeholder.com/600/fdf73e",
    "thumbnailUrl": "https://via.placeholder.com/150/fdf73e"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 17,
    'itemColor': Colors.white,
    "title": "natus doloribus necessitatibus ipsa",
    "url": "https://via.placeholder.com/600/9c184f",
    "thumbnailUrl": "https://via.placeholder.com/150/9c184f"
  },
  {
    'isFav':false,
    "albumId": 1,
    'itemColor': Colors.white,
    "id": 18,
    "title": "laboriosam odit nam necessitatibus et illum dolores reiciendis",
    "url": "https://via.placeholder.com/600/1fe46f",
    "thumbnailUrl": "https://via.placeholder.com/150/1fe46f"
  },
  {
    'isFav':false,
    "albumId": 1,
    'itemColor': Colors.white,
    "id": 19,
    "title": "perferendis nesciunt eveniet et optio a",
    "url": "https://via.placeholder.com/600/56acb2",
    "thumbnailUrl": "https://via.placeholder.com/150/56acb2"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 20,
    'itemColor': Colors.white,
    "title": "assumenda voluptatem laboriosam enim consequatur veniam placeat reiciendis error",
    "url": "https://via.placeholder.com/600/8985dc",
    "thumbnailUrl": "https://via.placeholder.com/150/8985dc"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 21,
    'itemColor': Colors.white,
    "title": "ad et natus qui",
    "url": "https://via.placeholder.com/600/5e12c6",
    "thumbnailUrl": "https://via.placeholder.com/150/5e12c6"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 22,
    'itemColor': Colors.white,
    "title": "et ea illo et sit voluptas animi blanditiis porro",
    "url": "https://via.placeholder.com/600/45601a",
    "thumbnailUrl": "https://via.placeholder.com/150/45601a"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 23,
    'itemColor': Colors.white,
    "title": "harum velit vero totam",
    "url": "https://via.placeholder.com/600/e924e6",
    "thumbnailUrl": "https://via.placeholder.com/150/e924e6"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 24,
    'itemColor': Colors.white,
    "title": "beatae officiis ut aut",
    "url": "https://via.placeholder.com/600/8f209a",
    "thumbnailUrl": "https://via.placeholder.com/150/8f209a"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 25,
    'itemColor': Colors.white,
    "title": "facere non quis fuga fugit vitae",
    "url": "https://via.placeholder.com/600/5e3a73",
    "thumbnailUrl": "https://via.placeholder.com/150/5e3a73"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 26,
    'itemColor': Colors.white,
    "title": "asperiores nobis voluptate qui",
    "url": "https://via.placeholder.com/600/474645",
    "thumbnailUrl": "https://via.placeholder.com/150/474645"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 27,
    'itemColor': Colors.white,
    "title": "sit asperiores est quos quis nisi veniam error",
    "url": "https://via.placeholder.com/600/c984bf",
    "thumbnailUrl": "https://via.placeholder.com/150/c984bf"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 28,
    'itemColor': Colors.white,
    "title": "non neque eligendi molestiae repudiandae illum voluptatem qui aut",
    "url": "https://via.placeholder.com/600/392537",
    "thumbnailUrl": "https://via.placeholder.com/150/392537"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 29,
    'itemColor': Colors.white,
    "title": "aut ipsam quos ab placeat omnis",
    "url": "https://via.placeholder.com/600/602b9e",
    "thumbnailUrl": "https://via.placeholder.com/150/602b9e"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 30,
    'itemColor': Colors.white,
    "title": "odio enim voluptatem quidem aut nihil illum",
    "url": "https://via.placeholder.com/600/372c93",
    "thumbnailUrl": "https://via.placeholder.com/150/372c93"
  },
  {
    'isFav':false,
    "albumId": 1,
    "id": 31,
    'itemColor': Colors.white,
    "title": "voluptate voluptates sequi",
    "url": "https://via.placeholder.com/600/a7c272",
    "thumbnailUrl": "https://via.placeholder.com/150/a7c272"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 32,
    'itemColor': Colors.white,
    "title": "ad enim dignissimos voluptatem similique",
    "url": "https://via.placeholder.com/600/c70a4d",
    "thumbnailUrl": "https://via.placeholder.com/150/c70a4d"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 33,
    'itemColor': Colors.white,
    "title": "culpa ipsam nobis qui fuga magni et mollitia",
    "url": "https://via.placeholder.com/600/501fe1",
    "thumbnailUrl": "https://via.placeholder.com/150/501fe1"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 34,
    'itemColor': Colors.white,
    "title": "vitae est facere quia itaque adipisci perferendis id maiores",
    "url": "https://via.placeholder.com/600/35185e",
    "thumbnailUrl": "https://via.placeholder.com/150/35185e"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 35,
    'itemColor': Colors.white,
    "title": "tenetur minus voluptatum et",
    "url": "https://via.placeholder.com/600/c96cad",
    "thumbnailUrl": "https://via.placeholder.com/150/c96cad"
  },
  {'isFav':false,
    "albumId": 1,
    'itemColor': Colors.white,
    "id": 36,
    "title": "expedita rerum eaque",
    "url": "https://via.placeholder.com/600/4d564d",
    "thumbnailUrl": "https://via.placeholder.com/150/4d564d"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 37,
    'itemColor': Colors.white,
    "title": "totam voluptas iusto deserunt dolores",
    "url": "https://via.placeholder.com/600/ea51da",
    "thumbnailUrl": "https://via.placeholder.com/150/ea51da"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 38,
    'itemColor': Colors.white,
    "title": "natus magnam iure rerum pariatur molestias dolore nisi",
    "url": "https://via.placeholder.com/600/4f5b8d",
    "thumbnailUrl": "https://via.placeholder.com/150/4f5b8d"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 39,
    'itemColor': Colors.white,
    "title": "molestiae nam ullam et rerum doloribus",
    "url": "https://via.placeholder.com/600/1e71a2",
    "thumbnailUrl": "https://via.placeholder.com/150/1e71a2"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 40,
    'itemColor': Colors.white,
    "title": "est quas voluptates dignissimos sint praesentium nisi recusandae",
    "url": "https://via.placeholder.com/600/3a0b95",
    "thumbnailUrl": "https://via.placeholder.com/150/3a0b95"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 41,
    'itemColor': Colors.white,
    "title": "in voluptatem doloremque cum atque architecto deleniti",
    "url": "https://via.placeholder.com/600/659403",
    "thumbnailUrl": "https://via.placeholder.com/150/659403"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 42,
    'itemColor': Colors.white,
    "title": "voluptatibus a autem molestias voluptas architecto culpa",
    "url": "https://via.placeholder.com/600/ca50ac",
    "thumbnailUrl": "https://via.placeholder.com/150/ca50ac"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 43,
    'itemColor': Colors.white,
    "title": "eius hic autem ad beatae voluptas",
    "url": "https://via.placeholder.com/600/6ad437",
    "thumbnailUrl": "https://via.placeholder.com/150/6ad437"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 44,
    'itemColor': Colors.white,
    "title": "neque eum provident et inventore sed ipsam dignissimos quo",
    "url": "https://via.placeholder.com/600/29fe9f",
    "thumbnailUrl": "https://via.placeholder.com/150/29fe9f"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 45,
    'itemColor': Colors.white,
    "title": "praesentium fugit quis aut voluptatum commodi dolore corrupti",
    "url": "https://via.placeholder.com/600/c4084a",
    "thumbnailUrl": "https://via.placeholder.com/150/c4084a"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 46,
    'itemColor': Colors.white,
    "title": "quidem maiores in quia fugit dolore explicabo occaecati",
    "url": "https://via.placeholder.com/600/e9b68",
    "thumbnailUrl": "https://via.placeholder.com/150/e9b68"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 47,
    'itemColor': Colors.white,
    "title": "et soluta est",
    "url": "https://via.placeholder.com/600/b4412f",
    "thumbnailUrl": "https://via.placeholder.com/150/b4412f"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 48,
    'itemColor': Colors.white,
    "title": "ut esse id",
    "url": "https://via.placeholder.com/600/68e0a8",
    "thumbnailUrl": "https://via.placeholder.com/150/68e0a8"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 49,
    'itemColor': Colors.white,
    "title": "quasi quae est modi quis quam in impedit",
    "url": "https://via.placeholder.com/600/2cd88b",
    "thumbnailUrl": "https://via.placeholder.com/150/2cd88b"
  },
  {'isFav':false,
    "albumId": 1,
    "id": 50,
    'itemColor': Colors.white,
    "title": "et inventore quae ut tempore eius voluptatum",
    "url": "https://via.placeholder.com/600/9e59da",
    "thumbnailUrl": "https://via.placeholder.com/150/9e59da"
  },
  {'isFav':false,
    "albumId": 2,
    "id": 51,
    'itemColor': Colors.white,
    "title": "non sunt voluptatem placeat consequuntur rem incidunt",
    "url": "https://via.placeholder.com/600/8e973b",
    "thumbnailUrl": "https://via.placeholder.com/150/8e973b"
  },
  {'isFav':false,
    "albumId": 2,
    "id": 52,
    'itemColor': Colors.white,
    "title": "eveniet pariatur quia nobis reiciendis laboriosam ea",
    "url": "https://via.placeholder.com/600/121fa4",
    "thumbnailUrl": "https://via.placeholder.com/150/121fa4"
  },
  {'isFav':false,
  'itemColor': Colors.white,
    "albumId": 2,
    "id": 53,
    "title": "soluta et harum aliquid officiis ab omnis consequatur",
    "url": "https://via.placeholder.com/600/6efc5f",
    "thumbnailUrl": "https://via.placeholder.com/150/6efc5f"
  },
  {'isFav':false,
    "albumId": 2,
    "id": 54,
    'itemColor': Colors.white,
    "title": "ut ex quibusdam dolore mollitia",
    "url": "https://via.placeholder.com/600/aa8f2e",
    "thumbnailUrl": "https://via.placeholder.com/150/aa8f2e"
  },
  {'isFav':false,
    "albumId": 2,
    "id": 55,
    'itemColor': Colors.white,
    "title": "voluptatem consequatur totam qui aut iure est vel",
    "url": "https://via.placeholder.com/600/5e04a4",
    "thumbnailUrl": "https://via.placeholder.com/150/5e04a4"
  },
  {'isFav':false,
    "albumId": 2,
    "id": 56,
    'itemColor': Colors.white,
    "title": "vel voluptatem esse consequuntur est officia quo aut quisquam",
    "url": "https://via.placeholder.com/600/f9f067",
    "thumbnailUrl": "https://via.placeholder.com/150/f9f067"
  },
  {'isFav':false,
    "albumId": 2,
    "id": 57,
    "title": "vero est optio expedita quis ut molestiae",
    "url": "https://via.placeholder.com/600/95acce",
    "thumbnailUrl": "https://via.placeholder.com/150/95acce"
  },
  {'isFav':false,
  'itemColor': Colors.white,
    "albumId": 2,
    "id": 58,
    "title": "rem pariatur facere eaque",
    "url": "https://via.placeholder.com/600/cde4c1",
    "thumbnailUrl": "https://via.placeholder.com/150/cde4c1"
  },
  {'isFav':false,
    "albumId": 2,
    "id": 59,
    'itemColor': Colors.white,
    "title": "modi totam dolor eaque et ipsum est cupiditate",
    "url": "https://via.placeholder.com/600/a46a91",
    "thumbnailUrl": "https://via.placeholder.com/150/a46a91"
  },
  {'isFav':false,
    "albumId": 2,
    "id": 60,
    'itemColor': Colors.white,
    "title": "ea enim temporibus asperiores placeat consectetur commodi ullam",
    "url": "https://via.placeholder.com/600/323599",
    "thumbnailUrl": "https://via.placeholder.com/150/323599"
  },

];